Repository noko1024/MyListCreate, pull requests merged in 2021-09, with the labels that each got.

#16 bug fix
  niconico.py
Labels: bug

#15 マイリスの上限値に合わせて各処理値を修正
  .github/ISSUE_TEMPLATE/bug_report.md
  niconico.py
Labels: bug

#20 fix
  niconico.py
Labels: bug

#19 マイリス除外命令の修正
  niconico.py
Labels: bug

#21 マイリストの存在確認を行う関数を追加しました
  niconico.py
Labels: bug, enhancement

#22 tkinterによるGUI化
  .gitignore
  DBcreate.py
  Twindow.py
  niconico.py
Labels: enhancement

#23 検索システムの更新
  niconico.py
Labels: enhancement

#24 fix
  niconico.py
Labels: bug
